### ISSUE TITLE
権限絞ったほうがいいっすよ

### ISSUE THREAD

**Issue by kinnkuro** [YohYasushi/Renshu#1]
誰でも書き込める設定にするとトラブルの元なので

**Comment by YohYasushi** [comment]
関連書籍をみても、publicで良いと書いてあったんですが…。

**Comment by kinnkuro** [comment]
エンタープライズ版の運用の感覚でコメントしたんですが、
個人の公開リポジトリならいいんですかね？

勉強になりました
